### PR TITLE
Update PersonCardFields to truncate at 80 characters

### LINKED ISSUE #158: All fields could be truncated
Currently if any of the fields other than remark are too long, they are not truncated which decreases readability. Truncating all fields would greatly increase readability and if there is any missing information, users can use the ViewCommand instead.

image

### PR DESCRIPTION
**Pull request by colinhia**
image
Closes #158

### CODE REVIEW

**Comment by itsme-zeix** [comment]
image

I pulled your branch to test, I think we can try to increase past 50 characters! This screenshot is the app at the smallest possible window size possible and there is still quite a bit of space in the row for more text!    

For the remarks icon, I think `far-comment-dots` from `FontAwesome5` might be more suitable. Hashtag sort of implies something like a tag.

Do also remember to update the name title and check with varying window sizes~

**Comment by colinhia** [comment]
image
 Updated the Icon and Character limit (to 80)

**Review by FionaQY — APPROVED** [review]
LGTM. Very clean code

**Review by itsme-zeix — APPROVED** [review]
LGTM!

**Pull request merged**
