### PR TITLE
Add filter command (Converted from existing find command)

### LINKED ISSUE #41: Find command should be renamed to Filter
Renaming is required to match requirements of AgentAssist (instead of AddressBook)

### PR DESCRIPTION
**Pull request by itsme-zeix**
Closes #41 

Modifies existing find function to filter.

Original logic allows users to provide multiple keywords. The addressbook searches for names with words that exactly match the keyword. New logic simply searches for substring within the names.

### CODE REVIEW

**Comment by iamdiluxedbutcooler** [comment]
NOT LGTM

**Comment by iamdiluxedbutcooler** [comment]
>:((((

**Comment by iamdiluxedbutcooler** [comment]
MR TANNNNN

**Review by ZShunRen — APPROVED** [review]
LGTM

**Pull request merged**
